name: Rust

on:
  pull_request: {}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Lint
      run: cargo fmt --all -- --check
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
